Repository open205/schema-205, pull requests merged in 2019-12, with the labels that each got.

#4 Clean up and fixes
  examples/json/RS0003ExampleFile-continuous.a205.json
  examples/json/RS0003ExampleFile-discrete.a205.json
  schema/RS0002.schema.json
  schema/RS0003.schema.json
Labels: bug

#5 AHRI elements
  schema/RS0001.schema.json
  schema/RS0002.schema.json
  schema/RS0003.schema.json
Labels: enhancement

#6 Add readme git instructions
  README.md
Labels: documentation
